modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/suspicious_pots/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:decorated_pot"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Update-Checker/main/SuspiciousPots.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/suspicious_pots"
logoFile="logo.png"
credits="@gaspoweredpick for the idea"
authors="${mod_authors}"
description='''This mod sometimes releases small monsters such as silverfish and baby husks when destroying pots!'''


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${mc_version_range}"
ordering="NONE"
side="BOTH"

