modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/suspicious_pots/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
itemIcon="minecraft:decorated_pot"
updateJSONURL="https://raw.githubusercontent.com/XxRexRaptorxX/Suspicious-Pots/refs/heads/main/versions.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/suspicious_pots"
logoFile="logo.png"
credits="@gaspoweredpick for the idea"
authors="${mod_authors}"
description='''This mod sometimes spawns small monsters such as silverfish, endermites or baby husks when destroying pots!'''

[modproperties.${mod_id}]
configuredBackground="minecraft:textures/entity/decorated_pot/danger_pottery_pattern.png"


[[dependencies.${mod_id}]]
modId="neoforge"
mandatory=true
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
mandatory=true
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="magmacore"
referralUrl="https://www.curseforge.com/minecraft/mc-mods/magma-core"
reason="Provides basic code and features such as update-checker"
type="required"
versionRange="${magmacore_version_range}"
ordering="AFTER"
side="BOTH"